name: Java CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone-down: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download the code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: my-step
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Docker upload
        uses: actions/upload-artifact@v2
        with:
          name: Docker-image
          path: .
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download tests
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: testing
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Docker-image:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Download docker
        uses: actions/download-artifact@v2
        with:
          name: Docker-image
          path: .
      - run: bash ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA"
      - run: bash ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA"
  Component-test:
    needs: Docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Download docker
        uses: actions/download-artifact@v2
        with:
          name: Docker-image
          path: .
      - name: running a component test 
        run: bash ci/component-test.sh && export GIT_COMMIT="GA-$GITHUB_SHA"